export class V3StackingList {
  static stackingList() {
    return [
      {
        round: 53,
        startBlock: 777350,
        endBlock: 779449,
        endBlockDate: '2023-03-05T09:05:30.000Z',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 54,
        startBlock: 779450,
        endBlock: 781549,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 55,
        startBlock: 781550,
        endBlock: 783649,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 56,
        startBlock: 783650,
        endBlock: 785749,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 57,
        startBlock: 785750,
        endBlock: 787849,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 58,
        startBlock: 787850,
        endBlock: 789949,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 59,
        startBlock: 789950,
        endBlock: 792049,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 60,
        startBlock: 792050,
        endBlock: 794149,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 61,
        startBlock: 794150,
        endBlock: 796249,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 62,
        startBlock: 796250,
        endBlock: 798349,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 63,
        startBlock: 798350,
        endBlock: 800449,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 64,
        startBlock: 800450,
        endBlock: 802549,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 65,
        startBlock: 802550,
        endBlock: 804649,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 66,
        startBlock: 804650,
        endBlock: 806749,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 67,
        startBlock: 806750,
        endBlock: 808849,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 68,
        startBlock: 808850,
        endBlock: 810949,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 69,
        startBlock: 810950,
        endBlock: 813049,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 70,
        startBlock: 813050,
        endBlock: 815149,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 71,
        startBlock: 815150,
        endBlock: 817249,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 72,
        startBlock: 817250,
        endBlock: 819349,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 73,
        startBlock: 819350,
        endBlock: 821449,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 74,
        startBlock: 821450,
        endBlock: 823549,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 75,
        startBlock: 823550,
        endBlock: 825649,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 76,
        startBlock: 825650,
        endBlock: 827749,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 77,
        startBlock: 827750,
        endBlock: 829849,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 78,
        startBlock: 829850,
        endBlock: 831949,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 79,
        startBlock: 831950,
        endBlock: 834049,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 80,
        startBlock: 834050,
        endBlock: 836149,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 81,
        startBlock: 836150,
        endBlock: 838249,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 82,
        startBlock: 838250,
        endBlock: 840349,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 83,
        startBlock: 840350,
        endBlock: 842449,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 84,
        startBlock: 842450,
        endBlock: 844549,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 85,
        startBlock: 844550,
        endBlock: 846649,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 86,
        startBlock: 846650,
        endBlock: 848749,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 87,
        startBlock: 848750,
        endBlock: 850849,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 88,
        startBlock: 850850,
        endBlock: 852949,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 89,
        startBlock: 852950,
        endBlock: 855049,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 90,
        startBlock: 855050,
        endBlock: 857149,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 91,
        startBlock: 857150,
        endBlock: 859249,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 92,
        startBlock: 859250,
        endBlock: 861349,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 93,
        startBlock: 861350,
        endBlock: 863449,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 94,
        startBlock: 863450,
        endBlock: 865549,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 95,
        startBlock: 865550,
        endBlock: 867649,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 96,
        startBlock: 867650,
        endBlock: 869749,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 97,
        startBlock: 869750,
        endBlock: 871849,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 98,
        startBlock: 871850,
        endBlock: 873949,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 99,
        startBlock: 873950,
        endBlock: 876049,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
      {
        round: 100,
        startBlock: 876050,
        endBlock: 878149,
        endBlockDate: '',
        stackedCoins: 0,
        claimedRewards: 0,
        claimDate: '',
        canClaimCoin: '',
      },
    ];
  }
}
