name: Publish site to Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Find and Replace homepage in packages.json
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "[HomePage]"
          replace: "https://fatstx.github.io/FatStx/"
          regex: false
          include: "package.json"
      - name: install packages
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
            branch: gh-pages
            folder: build
            token: ${{ secrets.PAT_GHPAGES_PUBLISH }}
            repository-name: "FatStx/FatStx"
        # run: yarn deploy
        # env:  PAT_GHPAGES_PUBLISH: ${{ secrets.PAT_GHPAGES_PUBLISH }}
