name: Publish site to https://fatstx.github.io/FatStx/

on:
  workflow_dispatch:

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: install packages
        run: yarn install
      - name: deploy
        run: yarn deploy
        env:
          PAT_GHPAGES_PUBLISH: ${{ secrets.PAT_GHPAGES_PUBLISH }}
