name: Publish site to https://stacksboard.github.io/

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: install packages
        run: yarn install
      - name: deploy
        run: yarn deploy
